# Generated by Django 6.1 on 2026-09-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_pedido_cliente_remove_itempedido_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='novidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque (destaque para clientes logados)'),
        ),
    ]
